### ISSUE TITLE
Cover worker API

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/performance#13]
We should cover worker API under https://guides.gradle.org/performance/#parallel_execution

cc @ghale @eskatos @oehme

**Comment by Thunderforge** [comment]
Given that no reasons have been given in the last 9 months, I'm guessing it would be okay to add this? I would love to see the guide improved to explain how this works.

**Comment by adammurdoch** [comment]
I wouldn't add the worker API under 'easy improvements' though. It's not really a feature that build authors would used. Instead, we might add a section about 'things that plugin authors can do to improve performance for people using their plugins' and mention the worker API there (and build caching, incremental tasks, etc).

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #220](https://github.com/gradle/guides/issues/220) via [**ZenHub**](https://www.zenhub.com/)
