### ISSUE TITLE
Mention negative impacts of virus scanners

### ISSUE THREAD

**Issue by eriwen** [gradle-guides/performance#14]
We've had customers who complain about `clean` time turn out to have virus scanners that significantly degrade build perf.

**Comment by Thunderforge** [comment]
Is this still an issue? Is there any hard evidence that virus scanners are significantly degrading the amount of time that `clean` takes to execute?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #222](https://github.com/gradle/guides/issues/222) via [**ZenHub**](https://www.zenhub.com/)
