### ISSUE TITLE
Update the guide with 4.0

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/performance#2]
- Compile-avoidance
     - Separate annotation processors from compile classpath for optimal performance
- Java incremental compilation
     - No longer incubating
- Java Library plugin that
     - Improved compilation speed

For more information see [3.4 release notes](https://docs.gradle.org/3.4/release-notes.html).

**Comment by pioterj** [comment]
@oehme I think it would make sense for the Performance Team to write the first draft that @kousen or @ysb33r would polish later on. Note that we are planning to properly launch and start promoting the guides in May. I see this as one of the critical stories for this to happen.

**Comment by oehme** [comment]
Makes sense, feel free to assign this to me for now.

**Comment by pioterj** [comment]
@oehme Looks like you need to join gradle-guides GitHub organization first. Please assign yourself once you accept my invitation.

**Comment by pioterj** [comment]
@oehme We are actually very close to the launch of the guides. Will you or someone from performance team be able to look into this soon?

**Comment by oehme** [comment]
Yes, we should have some bandwidth for this. What's the target date for the launch?

**Comment by pioterj** [comment]
We'll launch as soon as all stories in https://github.com/gradle/guides-private/issues/20 are completed. I'd say in the next week or two.

**Comment by oehme** [comment]
Upgrade to 3.5 done here: https://github.com/gradle-guides/performance/pull/6

**Comment by oehme** [comment]
Upgrade to 4.0: https://github.com/gradle-guides/performance/pull/10

**Comment by ysb33r** [comment]
I've merged @oehme 's #10. Replaying all of the testing on top of that.

**Comment by pioterj** [comment]
Can we close this now?
