### ISSUE TITLE
Mention build cache under the "easy improvements" section

### ISSUE THREAD

**Issue by big-guy** [gradle-guides/performance#25]
Our [easy improvements](https://guides.gradle.org/performance/#easy_improvements) recommend using the newest version of Gradle, the latest JDK and enabling `--parallel`.  Enabling `--build-cache` is also a big improvement that could be made to most builds.  The guide does mention the build cache, but it's much further down and buried in a section about task execution.

I think we should just recommend trying it, link to the documentation for the build cache, link to the section in the performance guide and link to our blog post that shows the improvement we saw in the gradle/gradle build.  Even using just the local build cache can be a big improvement for some people.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #258](https://github.com/gradle/guides/issues/258) via [**ZenHub**](https://www.zenhub.com/)
