### ISSUE TITLE
Suggest modularizing into separate projects to improve perf

### ISSUE THREAD

**Issue by eriwen** [gradle-guides/performance#27]
Modularizing allows for finer-grained caching/up-to-date checks and isolating sources having annotation processing. 

This isn't yet mentioned in the performance guide and should be. It's much more impactful than a bunch of suggestions on it.

**Comment by eriwen** [comment]
For example, it's much better to, say, extract a small library from a project and convert that to Kotlin, than to simply apply the Kotlin plugin and put those sources in `src/main/java`

**Comment by CristianGM** [comment]
Again, even if that's true, one of the most important benefits of modularization, is Compile Avoidance, and it only works with Java.
Then one small change in a module can make all the other modules to recompile ( assuming they depend on it ).

IMHO Compila Avoidance is the most important feature to improve incremental compilation on Kotlin projects, and not having it makes modularization not as good as it was with java.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #262](https://github.com/gradle/guides/issues/262) via [**ZenHub**](https://www.zenhub.com/)
