### ISSUE TITLE
Cover build cache

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/performance#3]
See the documentation at https://docs.gradle.org/nightly/userguide/build_cache.html.

Probably good timing to publish this content would be once 3.5 is out.

**Comment by pioterj** [comment]
@lptr I think it would make sense for the cache team to write the first draft for @kousen or @ysb33r to polish later. Note that we are planning to properly launch and start promoting the guides in May. I see this as one of the critical stories for this to happen.

**Comment by pioterj** [comment]
The key topical guide will be written by the cache team: https://github.com/gradle/task-output-cache/issues/110. We should support it (review, copy edit, help to publish).

We should also think about a getting started guide or two covering the cache.

**Comment by pioterj** [comment]
We should definitely do this for 4.0 GA. I hope that guides launch will be sooner than that so I'm removing it from the epic.

**Comment by lptr** [comment]
Added link to the build cache guide: https://github.com/gradle-guides/performance/pull/8
