### ISSUE TITLE
Guidelines for multiple executors on 1 Master Jenkins Node?

### ISSUE THREAD

**Issue by mrk-han** [gradle-guides/performance#34]
I am wondering if there are any resources available that would help with running on Jenkins and optimizing 1 Node with several Executors. I am wanting to follow these guidelines but unsure if they would also apply to my situation.

Perhaps there should be warning about not following certain things when running on Jenkins w/ multiple executors per node? 

In my case, the node is a static Mac Pro.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #299](https://github.com/gradle/guides/issues/299) via [**ZenHub**](https://www.zenhub.com/)
