### ISSUE TITLE
Potential Contradiction in Allocated Heap Statements 

### ISSUE THREAD

**Issue by mrk-han** [gradle-guides/performance#35]
https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:how_much_memory_does_the_daemon_use_and_can_i_give_it_more
![image](https://user-images.githubusercontent.com/22263679/64460567-b29a3d00-d0c8-11e9-9c1f-6812ccaa8577.png)

**vs**

https://guides.gradle.org/performance/#adjust_the_daemon_s_heap_size
![image](https://user-images.githubusercontent.com/22263679/64460548-a2825d80-d0c8-11e9-95e7-a49b5a5df9da.png)

Is this a contradiction?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #300](https://github.com/gradle/guides/issues/300) via [**ZenHub**](https://www.zenhub.com/)
